version: "3.9"
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: localpw
  app:
    build: .
    environment:
      APP_ENVIRONMENT: development
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: localpw
      DATABASE_HOST: database
    ports:
      - "3000:3000"
    links:
      - "database:database"
    depends_on:
      - database
    volumes:
    - ".:/app"
    working_dir: /app
