version: '2'

expansions: 5

tasks:

  lint-js:
    desc: lint javascript with 
    cmds:
      - cmd: docker compose -f lint-compose.yaml run javascript


  lint-ruby:
    desc: lint ruby with rubocop
    cmds:
      - cmd: docker compose -f lint-compose.yaml run ruby

  update-js:
    desc: lint javascript with 
    cmds:
      - cmd: docker compose -f update-compose.yaml run javascript


  update-ruby:
    desc: lint ruby with rubocop
    cmds:
      - cmd: docker compose -f update-compose.yaml run ruby

  server:
    desc: run application locally
    cmds:
      - cmd: docker compose up --build --force-recreate