# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rubocop', '~> 0.56.0', require: false
gem 'test-unit'
gem 'nokogiri'
gem 'typhoeus'
gem 'bundler-audit'
gem 'sinatra-activerecord'
gem 'pg'
