apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: movie-pile
spec:
  description: movie-pile
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
    - name: short-revision
      type: string
    - name: branch
      type: string
    - name: default-branch
      type: string
      default: main
    - name: enable-notifications
      default: true
    - name: repo-slug
      default: itsmethemojo/movie-pile
    - name: status-context
      default: test-and-publish
    - name: tekton-url
      type: string
    - name: lint-ruby-image
      type: string
      default: pipelinecomponents/rubocop
    - name: lint-javascript-image
      type: string
      default: node:14.14-stretch
    - name: kaniko-image
      type: string
      default: gcr.io/kaniko-project/executor:v1.23.2
    - name: publish-image
      type: string
      default: ghcr.io/itsmethemojo/movie-pile
    - name: publish-tag-prefix
      type: string
      default: ""
    - name: pipeline-mode
      default: "default"
  workspaces:
    - name: source_code
    - name: docker_config
  tasks:
    - name: set-pending-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.repo-slug)
        - name: SHA
          value: $(params.revision)
        - name: DESCRIPTION
          value: "test pipeline started"
        - name: CONTEXT
          value: $(params.status-context)
        - name: STATE
          value: pending
        - name: TARGET_URL
          value: $(params.tekton-url)
      taskRef:
        Name: github-set-status
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source_code
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: lint-ruby
      runAfter: ["fetch-source"]
      taskRef:
        name: movie-pile-lint-ruby
      workspaces:
        - name: source
          workspace: source_code
      params:
        - name: image
          value: $(params.lint-ruby-image)
      when:
        - input: $(params.pipeline-mode)
          operator: in
          values: ["only-pusblish-image"]
    - name: lint-javascript
      runAfter: ["lint-ruby"]
      taskRef:
        name: movie-pile-lint-javascript
      workspaces:
        - name: source
          workspace: source_code
      params:
        - name: image
          value: $(params.lint-javascript-image)
      when:
        - input: $(params.pipeline-mode)
          operator: in
          values: ["only-pusblish-image"]
    - name: kaniko-dryrun
      runAfter: ["lint-javascript"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: source_code
        - name: dockerconfig
          workspace: docker_config
      params:
        - name: BUILDER_IMAGE
          value: $(params.kaniko-image)
        - name: IMAGE
          value: "$(params.publish-image):$(params.publish-tag-prefix)sha-$(params.short-revision)"
        - name: EXTRA_ARGS
          value:
            - --no-push
      when:
        - input: $(params.branch)
          operator: notin
          values: ["$(params.default-branch)"]
    - name: kaniko
      runAfter: ["lint-javascript"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: source_code
        - name: dockerconfig
          workspace: docker_config
      params:
        - name: BUILDER_IMAGE
          value: $(params.kaniko-image)
        - name: IMAGE
          value: "$(params.publish-image):$(params.publish-tag-prefix)sha-$(params.short-revision)"
      when:
        - input: $(params.branch)
          operator: in
          values: ["$(params.default-branch)"]
  finally:
    - name: set-failed-status
      when:
        - input: $(tasks.status)
          operator: in
          values: ["Failed"]
        - input: $(params.enable-notifications)
          operator: in
          values: ["true"]
      params:
        - name: REPO_FULL_NAME
          value: $(params.repo-slug)
        - name: SHA
          value: $(params.revision)
        - name: DESCRIPTION
          value: "a task failed"
        - name: CONTEXT
          value: $(params.status-context)
        - name: STATE
          value: failure
        - name: TARGET_URL
          value: $(params.tekton-url)
      taskRef:
        Name: github-set-status
    - name: set-success-status
      when:
        - input: $(tasks.status)
          operator: in
          values: ["Completed"]
        - input: $(params.enable-notifications)
          operator: in
          values: ["true"]
      params:
        - name: REPO_FULL_NAME
          value: $(params.repo-slug)
        - name: SHA
          value: $(params.revision)
        - name: DESCRIPTION
          value: "all tasks have succeeded"
        - name: CONTEXT
          value: $(params.status-context)
        - name: STATE
          value: success
        - name: TARGET_URL
          value: $(params.tekton-url)
      taskRef:
        Name: github-set-status