apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: Task
metadata:
  name: movie-pile-lint-javascript
spec:
  params:
    - name: image
      type: string
  workspaces:
    - name: source
  steps:
    - name: test
      workingDir: $(workspaces.source.path)
      image: "$(params.image)"
      script: |-
        #!/bin/sh
        npm install --quiet && \
        echo "[INFO] run jscs on views/javascript"  && \
        node_modules/jscs/bin/jscs views/javascript && \
        echo "[INFO] run jshint on views/javascript"  && \
        node_modules/jshint/bin/jshint views/javascript
