app:
  nameOverride: movie-pile

  image:
    repository: ghcr.io/itsmethemojo/movie-pile
    tag: "sha-7db386d"

  containerPort: 3000

  env:
    DATABASE_HOST: movie-pile-database
    DATABASE_NAME: movie-pile
    DATABASE_USERNAME: movie-pile
    CACHE_PATH: /cache

  persistentVolumeClaims:
  - name: cache
    # -- mount a pvc for the cache directory
    mountPath: /cache
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

postgresql:
  # -- to use a separate deployed database set to false here
  enabled: true
  fullnameOverride: movie-pile-database
  primary:
    persistence:
      # -- for production use persistence should be enabled
      enabled: false
  auth:
    database: movie-pile
    username: movie-pile
