# this is needed because the docker image multi arch build seems not to work properly
name: kaniko

on:
  push:
    branches:
      - 'main'

jobs:
  kaniko:
    runs-on: [ "self-hosted", "ARM64", "Linux" ]
    container: ghcr.io/itsmethemojo/kaniko-github-actions-image:sha-034dcf8
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: kaniko build
        run: >-
          mkdir -p /kaniko/.docker/ &&
          echo "{\"auths\":{\"${{ env.REGISTRY }}\":{\"username\":\"${{ github.actor }}\",\"password\": \"${{ secrets.GITHUB_TOKEN }}\"}}}"  > /kaniko/.docker/config.json &&
          /kaniko/executor
          --context $(pwd)
          --destination "${REGISTRY}/${IMAGE_NAME}:sha-${GITHUB_SHA}"
          --destination "${REGISTRY}/${IMAGE_NAME}:sha-$(echo ${GITHUB_SHA} | cut -c -7)"

        # use same hash formats as standard docker build action 
