name: Tests

on:
  push:
  schedule:
    - cron: "0 11 7 * *"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: download task
      run: |
        wget https://taskfile.dev/install.sh
        chmod +x install.sh
        ./install.sh -b $(pwd)
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Build and test with Rake
      run: |
        gem install bundler
        BUNDLE_GEMFILE=.dckrz/config/docker/testing/Gemfile bundle install --jobs 4 --retry 3
        .dckrz/scripts/audit.sh && .dckrz/scripts/checkstyle.sh && .dckrz/scripts/unittest.sh
    - name: run js-lint
      run: |
        TASK_BINARY=$(pwd)/task $(pwd)/task dz:init
        TASK_BINARY=$(pwd)/task $(pwd)/task lint-js
